### ISSUE TITLE
New things recognition algorithms research and development

### ISSUE THREAD

**Issue by 3Dpass** [3Dpass/pass3d#4]
Implementation of new recognition algorithms into pass3d, which is the main part of 3DPass blockchain network, is the essential challenge we are passionate to solve, meaning the Global digital transformation of things.

**Types of things to recognize:** 
3D objects, 2D objects (drawings), 2D fingerprints, face recognition, voice, melody, radio signal, everything recognizable by means of machine processing. 

Every object, transformed by 3DPass, has its own unique and stable identity called HASH ID the object might be recognized by. By means of creation and implementation new recognition algorithms into our network, we are building this bridge between decentralized blockchain digital space and trillion deals making in real all over the world.

**Comment by PaulSff** [comment]
Should be more accurate
